import Foundation

struct DiningHallDirectory {
    static let all: [DiningHall] = [
        // Columbia dining halls
        DiningHall(
            id: "john_jay",
            name: "John Jay Dining Hall",
            campus: "Columbia",
            latitude: 40.8065,
            longitude: -73.9632,
            active: true,
            price: .standard,
            geofenceRadius: 80,
            address: "519 W 114th St, New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "jjs_place",
            name: "JJ’s Place",
            campus: "Columbia",
            latitude: 40.8065,
            longitude: -73.9632,
            active: true,
            price: .standard,
            geofenceRadius: 70,
            address: "519 W 114th St (Lower Level), New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "ferris_booth",
            name: "Ferris Booth Commons",
            campus: "Columbia",
            latitude: 40.8074,
            longitude: -73.9637,
            active: true,
            price: .standard,
            geofenceRadius: 80,
            address: "2920 Broadway, New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "faculty_house",
            name: "Faculty House",
            campus: "Columbia",
            latitude: 40.8090,
            longitude: -73.9615,
            active: true,
            price: .standard,
            geofenceRadius: 80,
            address: "64 Morningside Dr, New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "chef_mikes",
            name: "Chef Mike’s Sub Shop",
            campus: "Columbia",
            latitude: 40.8086,
            longitude: -73.9630,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "2920 Broadway (Lerner Hall), New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "chef_dons",
            name: "Chef Don’s Pizza Pi (featuring Blue Java)",
            campus: "Columbia",
            latitude: 40.8086,
            longitude: -73.9631,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "2920 Broadway (Lerner Hall), New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "grace_dodge",
            name: "Grace Dodge Dining Hall",
            campus: "Columbia",
            latitude: 40.8101,
            longitude: -73.9633,
            active: true,
            price: .standard,
            geofenceRadius: 70,
            address: "509 W 121st St, New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "johnnys_truck",
            name: "Johnny’s Food Truck",
            campus: "Columbia",
            latitude: 40.8056,
            longitude: -73.9650,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "Broadway & W 114th St, New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "robert_smith",
            name: "Robert F. Smith Dining Hall",
            campus: "Columbia",
            latitude: 40.8168,
            longitude: -73.9570,
            active: true,
            price: .standard,
            geofenceRadius: 80,
            address: "1220 Amsterdam Ave, New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        DiningHall(
            id: "fac_shack",
            name: "The Fac Shack",
            campus: "Columbia",
            latitude: 40.8092,
            longitude: -73.9611,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "64 Morningside Dr, New York, NY 10027",
            dineOnCampusSiteId: nil,
            dineOnCampusLocationId: nil,
            affiliation: .columbia,
            defaultOpenState: true
        ),
        // Barnard dining halls
        DiningHall(
            id: "hewitt_dining",
            name: "Hewitt Dining",
            campus: "Barnard",
            latitude: 40.8095,
            longitude: -73.9633,
            active: true,
            price: .standard,
            geofenceRadius: 70,
            address: "3009 Broadway, New York, NY 10027",
            dineOnCampusSiteId: "5cb77d6e4198d40babbc28b5",
            dineOnCampusLocationId: "5d27a0461ca48e0aca2a104c",
            affiliation: .barnard,
            defaultOpenState: true
        ),
        DiningHall(
            id: "barnard_kosher",
            name: "Barnard Kosher @ Hewitt Food Hall",
            campus: "Barnard",
            latitude: 40.8095,
            longitude: -73.9633,
            active: true,
            price: .standard,
            geofenceRadius: 70,
            address: "3009 Broadway, New York, NY 10027",
            dineOnCampusSiteId: "5cb77d6e4198d40babbc28b5",
            dineOnCampusLocationId: "5d794b63c4b7ff15288ba3da",
            affiliation: .barnard,
            defaultOpenState: true
        ),
        DiningHall(
            id: "lefrak_center",
            name: "LeFrak Center",
            campus: "Barnard",
            latitude: 40.8100,
            longitude: -73.9637,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "35 Claremont Ave, New York, NY 10027",
            dineOnCampusSiteId: "5cb77d6e4198d40babbc28b5",
            dineOnCampusLocationId: "67252a74351d530746aa3f21",
            affiliation: .barnard,
            defaultOpenState: true
        ),
        DiningHall(
            id: "lizs_place",
            name: "Liz’s Place",
            campus: "Barnard",
            latitude: 40.8097,
            longitude: -73.9630,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "3009 Broadway, New York, NY 10027",
            dineOnCampusSiteId: "5cb77d6e4198d40babbc28b5",
            dineOnCampusLocationId: "5d79274b1ca48e10b33c4884",
            affiliation: .barnard,
            defaultOpenState: true
        ),
        DiningHall(
            id: "diana_center_cafe",
            name: "Diana Center Café",
            campus: "Barnard",
            latitude: 40.8100,
            longitude: -73.9630,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "3009 Broadway (Diana Center), New York, NY 10027",
            dineOnCampusSiteId: "5cb77d6e4198d40babbc28b5",
            dineOnCampusLocationId: "5d8775484198d40d7a0b8078",
            affiliation: .barnard,
            defaultOpenState: true
        ),
        DiningHall(
            id: "bubble_tea_sushi",
            name: "Barnard Dining Bubble Tea & Sushi Spot (Milstein)",
            campus: "Barnard",
            latitude: 40.8093,
            longitude: -73.9623,
            active: true,
            price: .standard,
            geofenceRadius: 60,
            address: "3009 Broadway (Milstein Center), New York, NY 10027",
            dineOnCampusSiteId: "5cb77d6e4198d40babbc28b5",
            dineOnCampusLocationId: "63e6c3b1351d53062192e8a4",
            affiliation: .barnard,
            defaultOpenState: true
        )
    ]
}

private extension DiningHallPrice {
    static let standard = DiningHallPrice(breakfast: 13.0, lunch: 17.5, dinner: 19.5)
}
